ProjectMohammadRepositry/Controllers/PromationBookController.cs
using Asp.Common.SessionConfig;
using Asp.DALL.Entites;
using Asp.DALL.Repositray;
using Microsoft.AspNetCore.Mvc;

namespace ProjectMohammadRepositry.Controllers
{
    public class PromationBookController : BaseController
    {
        private readonly IRepositoryBase<PromationBook> _repo;
        private readonly ISessionConfigService _sessionService;

        public PromationBookController(IRepositoryBase<PromationBook> repo, ISessionConfigService SessionService):base(SessionService)
        {
            _repo = repo;
            _sessionService = SessionService;
            
        }
        public async Task< IActionResult> Index()
        {
         
            return View();
        }
        public async Task<IActionResult> LoadDataGrid()
        {
            List<PromationBook> listpromation = await _repo.GetList();
            return Json(listpromation);
        }
        public async Task<IActionResult> Form(int ? id)
        {
            if (id == 0 || id==null)
            {
                return PartialView();
            }
            else
            {
                return PartialView(await _repo.GetOne(z => z.Id == id));
            }
        }
        [HttpPost]
        public async Task<IActionResult> Form(PromationBook pro)
        {
            bool done = false;
            if (pro.Id == 0 || pro.Id==null) { 
                done=await _repo.Add(pro);
            
            }
            else
            {
                done=await _repo.Update(pro);
            }
            return Json(done);

        }
        public async Task<IActionResult> Delete(int ? id)
        {

            return PartialView(await _repo.GetOne(z => z.Id == id));

        }
        [HttpPost]
        public async Task<IActionResult> Delete(PromationBook del)
        {
            bool done = false;
            await _repo.Delete(del);
            return Json(new {done=done});

        }

    }
}

ProjectMohammadRepositry/Views/PromationBook/Delete.cshtml
@model Asp.DALL.Entites.PromationBook


<h1>Are you sure???????</h1>

<form asp-controller="PromationBook" asp-action="Delete" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />

    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/PromationBook/Form.cshtml
@model Asp.DALL.Entites.PromationBook



<form asp-controller="PromationBook" asp-action="Form" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />
    <label class="form-group">BookName</label>
    <input class="form-control" type="text" asp-for="BookName" />
    <br />
    <label class="form-group">BookTitle</label>
    <input class="form-control" type="text" asp-for="BookTitle" />
    <br />
    <label class="form-group">PriceBook</label>
    <input class="form-control" type="number" asp-for="PriceBook" />
    <br />
    <label class="form-group">DescriptionBook</label>
    <input class="form-control" type="text" asp-for="DescriptionBook" />
    <br />
    <button class="btn btn-success"> save</button>
</form>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/PromationBook/Index.cshtml
<a href="javascript:void(0)" onclick="return OpenAddForm()" class="btn btn-primary" style=" margin-top: 4%; margin-bottom:10px">Create</a>
<table id="FormTable" class="table table-bordered table-striped  js-basic-example dataTable">
    <thead>
        <tr>
            <th>Id</th>
            <th>BookName</th>
            <th>BookTitle</th>
            <th>PriceBook</th>
            <th>DescriptionBook</th>
            <th>Update</th>
            <th>Delete</th>


        </tr>



    </thead>
    <tbody>
    </tbody>

</table>

<script>
    $(function () {
        LoadDataGrid();
    })
    var OpenAddForm = function () {

        $.ajax({
            url: '/PromationBook/Form',
            method: 'GET'
        }).done((data) => {
            $('#modal-trigger .title').text('Create');
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            toastr.error(response.responseText);
        })
    }
    var LoadDataGrid = function () {
        $.ajax({
            url: '/PromationBook/LoadDataGrid',
            method: 'GET',
        }).done((data) => {
            var dtObj = {
                data: data,
                retrieve: true,
                ordering: true,
                responsive: true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search..."
                },
                dom: 'Bfrtip',
                columns: [
                    { 'data': 'id' },
                    { 'data': 'bookName' },
                    { 'data': 'bookTitle' },
                    { 'data': 'priceBook' },
                    { 'data': 'descriptionBook' },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-success" onclick="return Edit(' + Data + ')">Edit</a>';
                            return rows;
                        }
                    },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-danger" onclick="return Delete(' + Data + ')">Delete</a>';
                            return rows;
                        }
                    }
                ]
            };

            $('#FormTable').dataTable().fnDestroy();
            $('#FormTable').dataTable(dtObj);
            $('#FormTable').css("width", "100%");
        });
    }
    var Delete = function (id) {
        $.ajax({
            url: '/PromationBook/Delete',
            method: 'GET',
            data: {
                id: id
            }
        }).done((data) => {
            $('#modal-trigger .title').text("Delete");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            console.log(response.responseText);
        })
    }

    var Edit = function (Id) {

        $.ajax({
            url: '/PromationBook/Form',
            method: 'GET',
            data: {
                Id: Id

            }
        }).done((data) => {
            $('#modal-trigger .title').text("Edit");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');

        }).fail(function (response) {
            toastr.error(response.responseText);
        })

    }

</script>