ProjectMohammadRepositry/Controllers/SurveyssController.cs
using Asp.Common.SessionConfig;
using Asp.DALL.Entites;
using Asp.DALL.Migrations;
using Asp.DALL.Repositray;
using Asp.DALL.Viewmodel;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
namespace ProjectMohammadRepositry.Controllers
{
    public class SurveyssController : BaseController
    {
        private readonly IRepositoryBase<Survey> _repo;
        private readonly IRepositoryBase<Gender> _genderlist;
        private readonly IRepositoryBase<ListBooks> _booklist;
        private IMapper _mapper;
        private readonly ISessionConfigService _sessionService;
        private IHostingEnvironment Environment;
        public SurveyssController(IRepositoryBase<Survey>repo,IRepositoryBase<Gender> genderlist,IRepositoryBase<ListBooks> booklist,IMapper mapper, IHostingEnvironment _environment, ISessionConfigService SessionService):base(SessionService)
        {
            _repo = repo;
            _genderlist = genderlist;
            _booklist = booklist;
            _mapper = mapper;
            Environment = _environment;
            _sessionService = SessionService;
            
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> LoadDataGrid()
        {
            List<Survey> ser = await _repo.GetList(includes: new List<string>{"Gender", "ListBooks" } );
            List<SurveyVM> viewmodel =  _mapper.Map<List<Survey>, List<SurveyVM>>(ser);
            foreach (var item in viewmodel)
            {
                item.Filepath = "../Attachment/" + item.Id + "." + item.Extention + "";

            }
            return Json(viewmodel);
        }
        public async Task<IActionResult> Form(int ? id)
         {
            SurveyVM vm=new SurveyVM();
            ViewData["gender"] = await _genderlist.GetList();
            ViewData["lists"] = await _booklist.GetList();

            if (id == 0 || id == null)
            {
                return PartialView();

            }
            else
            {
                Survey entity = await _repo.GetOne(z => z.Id == id);
                vm = _mapper.Map<Survey, SurveyVM>(entity);
               return PartialView(vm);
            }


        }
        [HttpPost]
        public async Task<IActionResult> Form(SurveyVM insertsurvey)
        {
            Survey model;
            model=_mapper.Map<SurveyVM,Survey>(insertsurvey);
            model.File = "../Attachment";
            var xx = Path.GetFileName(insertsurvey.Attach.FileName).Split(".");
            model.Extention = Path.GetFileName(insertsurvey.Attach.FileName).Split(".")[xx.Count() - 1];
            bool done = false;
            if (insertsurvey.Id == null || insertsurvey.Id==0) {
            
              done=await _repo.Add(model);
            }
            else
            {
                done=await _repo.Delete(model);
            }
            if (insertsurvey.Attach != null)
            {
                string path = Path.Combine(this.Environment.WebRootPath, "Attachment");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string name = model.Id.ToString() + "." + model.Extention;
                using (FileStream stream = new FileStream(Path.Combine(path, name), FileMode.Create))
                {
                    insertsurvey.Attach.CopyTo(stream);
                }
            }
            return Json(new {done});



        }
        public async Task<IActionResult> Delete(int ? id)
        {
            return PartialView(await _repo.GetOne(z => z.Id == id));
        }
        [HttpPost]
        public async Task<IActionResult> Delete(Survey del)
        {
            bool done = false;
            await _repo.Delete(del);
            return Json(new { done = done });

        }
    }
}

ProjectMohammadRepositry/Views/Surveyss/Delete.cshtml
@model Asp.DALL.Entites.Survey


<h1>Are you sure???????</h1>

<form asp-controller="Surveyss" asp-action="Delete" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />

    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/Surveyss/Form.cshtml
@using Asp.DALL.Entites;
@model Asp.DALL.Viewmodel.SurveyVM
@{
    var listgender = (List<Gender>)ViewData["gender"];
    var listbooks = (List<ListBooks>)ViewData["lists"];

}
<form asp-controller="Surveyss" asp-action="Form" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">

    <input type="hidden" asp-for="Id" />
    <label class="form-group">SurveyName</label>
    <input class="form-control" type="text" asp-for="SurveyName" />
    <br />
    <label class="form-group">PromationDescription</label>
    <input class="form-control" type="text" asp-for="SurveyDescription" />
    <br />
  
    <label class="form-group">Date</label>
    <input class="form-control" type="date" asp-for="Date" />
    <br />

    <label class="form-group">File</label>
    <input class="form-control" type="file" asp-for="Attach" />
    <input type="hidden" asp-for="File" />
    <input type="hidden" asp-for="Extention" />
    <br />
    <select class="form-control" asp-for="Genderid">

        <option value="">Select Gender</option>
        @foreach (var c in @listgender) // Print the list
        {
            <option value="@c.Id">@c.Name</option>
        }


    </select>
    <br />
    <select class="form-control" asp-for="Listid">

        <option value="">Select listbooks</option>
        @foreach (var c in @listbooks) // Print the list
        {
            <option value="@c.Id">@c.NameBooks</option>
        }


    </select>
    <br />
    <button class="btn btn-success"> save</button>
</form>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/Surveyss/Index.cshtml
<a href="javascript:void(0)" onclick="return OpenAddForm()" class="btn btn-primary" style=" margin-top: 4%; margin-bottom:10px">Create</a>
<table id="FormTable" class="table table-bordered table-striped  js-basic-example dataTable">
    <thead>
        <tr>
            <th>Id</th>
            <th>SurveyName</th>
            <th>SurveyDescription</th>
            <th>Date</th>
            <th>Gender</th>
            <th>listBooks</th>
            <th>File</th>
            <th>Update</th>
            <th>Delete</th>


        </tr>



    </thead>
    <tbody>
    </tbody>

</table>

<script>
    $(function () {
        LoadDataGrid();
    })
    var OpenAddForm = function () {

        $.ajax({
            url: '/Surveyss/Form',
            method: 'GET'
        }).done((data) => {
            $('#modal-trigger .title').text('Create');
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            toastr.error(response.responseText);
        })
    }
    var LoadDataGrid = function () {
        $.ajax({
            url: '/Surveyss/LoadDataGrid',
            method: 'GET',
        }).done((data) => {
            var dtObj = {
                data: data,
                retrieve: true,
                ordering: true,
                responsive: true,
                dom: 'Bfrtip',
                columns: [
                    { 'data': 'id' },
                    { 'data': 'surveyName' },
                    { 'data': 'surveyDescription' },
                    { 'data': 'date' },
                    { 'data': 'gender.name' },
                    { 'data': 'listid' },



                    {
                        'data': 'filepath',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-primary" target="_balnk" href="' + Data + '">attach</a>';


                            return rows;
                        }
                    },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-success" onclick="return Edit(' + Data + ')">Edit</a>';
                            return rows;
                        }
                    },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-danger" onclick="return Delete(' + Data + ')">Delete</a>';
                            return rows;
                        }
                    }
                ]
            };

            $('#FormTable').dataTable().fnDestroy();
            $('#FormTable').dataTable(dtObj);
            $('#FormTable').css("width", "100%");
        });
    }
    var Delete = function (id) {
        $.ajax({
            url: '/Surveyss/Delete',
            method: 'GET',
            data: {
                id: id
            }
        }).done((data) => {
            $('#modal-trigger .title').text("Delete");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            console.log(response.responseText);
        })
    }

    var Edit = function (Id) {

        $.ajax({
            url: '/Surveyss/Form',
            method: 'GET',
            data: {
                Id: Id

            }
        }).done((data) => {
            $('#modal-trigger .title').text("Edit");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');

        }).fail(function (response) {
            toastr.error(response.responseText);
        })

    }

</script>