ProjectMohammadRepositry/Controllers/FileextentionsController.cs
using Asp.Common.SessionConfig;
using Asp.DALL.Entites;
using Asp.DALL.Repositray;
using Asp.DALL.Viewmodel;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.Xml;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace ProjectMohammadRepositry.Controllers
{
    public class FileextentionsController : BaseController
    {
        private readonly IRepositoryBase<Fileextention> _repo;
        private readonly IRepositoryBase<Gender> _repoGender;
        private IHostingEnvironment Environment;
        private readonly IMapper _mapper;
        private readonly ISessionConfigService _sessionService;


        public FileextentionsController(IRepositoryBase<Fileextention> repo, IRepositoryBase<Gender> repoGender, IHostingEnvironment _environment
            , IMapper mapper, ISessionConfigService SessionService
            ):base(SessionService)
        {
             
            _repo = repo;
            _repoGender = repoGender;
            Environment = _environment;
            _mapper = mapper;
            _sessionService = SessionService;

        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> LoadDataGrid()
        {
           
            List<Fileextention> filees = await _repo.GetList(includes: new List<string> { "Gender" });
            //List<Fileextention> filees = await _repo.GetList();
            List<FileextentionVM> ViewModel = _mapper.Map<List<Fileextention>, List<FileextentionVM>>(filees);
            foreach (var item in ViewModel)
            {
                item.FilePath = "../Attachment/" + item.Id + "." + item.Extention + "";
            }
            return Json(ViewModel);
        }
        public async Task<IActionResult> Form(int ? id)

        {
            FileextentionVM ViewModel = new FileextentionVM();
            //var x = await _repoGender.GetList();
            ViewData["gender"] = await _repoGender.GetList();

            if (id == 0 || id==null) {

                return PartialView();
            }
            else
            {
                Fileextention entity = await _repo.GetOne(z => z.Id == id);
                ViewModel = _mapper.Map<Fileextention, FileextentionVM>(entity);
                return PartialView(ViewModel);

            }

        }
        [HttpPost]
        public async Task<IActionResult> Form(FileextentionVM Insert)
        {
            Fileextention model;
            model = _mapper.Map<FileextentionVM, Fileextention>(Insert);
            model.File = "../Attachment";
            var xx = Path.GetFileName(Insert.Attach.FileName).Split(".");
            model.Extention = Path.GetFileName(Insert.Attach.FileName).Split(".")[xx.Count()-1];
            bool done = false;
            if (Insert.Id == null || Insert.Id == 0) {
                done = await _repo.Add(model);
            }
            else
            {

                done = await _repo.Update(model);

            }
                if (Insert.Attach != null)
                {
                    string path = Path.Combine(this.Environment.WebRootPath, "Attachment");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                    }
                    string name = model.Id.ToString() + "." + model.Extention;
                    using (FileStream stream = new FileStream(Path.Combine(path, name), FileMode.Create))
                    {
                        Insert.Attach.CopyTo(stream);
                    }
                }


            
            return Json(new {done});

        }
        public async Task<IActionResult> Delete(int ? id)
        {
            return PartialView(await _repo.GetOne(z => z.Id == id));

        }
        [HttpPost]
        public async Task<IActionResult> Delete(Fileextention del)
        {
           bool done = false;
            await _repo.Delete(del);
            return Json(new {done=done});

        }
    }
}

ProjectMohammadRepositry/Views/Fileextentions/Delete.cshtml
@model Asp.DALL.Entites.Fileextention


<h1>Are you sure???????</h1>

<form asp-controller="Fileextentions" asp-action="Delete" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />

    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/Fileextentions/Form.cshtml
@using Asp.DALL.Entites;
@model Asp.DALL.Viewmodel.FileextentionVM
@{
    var ListOfGender = (List<Gender>)ViewData["gender"];
  

}
<form asp-controller="Fileextentions" asp-action="Form" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">
      
<input type="hidden" asp-for="Id" />
    <label class="form-group">Name</label>
    <input class="form-control" type="text" asp-for="Name" />
    <br />
    <label class="form-group">Description</label>
    <input class="form-control" type="text" asp-for="Description" />
    <br />
    <label class="form-group">Date</label>
    <input class="form-control" type="date" asp-for="Date" />
    <br />
    <label class="form-group">File</label>
    <input class="form-control" type="file" asp-for="Attach" />
    <input type="hidden" asp-for="File" />
    <input type="hidden" asp-for="Extention" />
    <br />
    <select class="form-control" asp-for="Genderid">

        <option value="">Select Gender</option>
        @foreach (var c in @ListOfGender) // Print the list
        {
            <option value="@c.Id">@c.Name</option>
        }


    </select>
    <br />
    <button class="btn btn-success"> save</button>
</form>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/Fileextentions/Index.cshtml
<a href="javascript:void(0)" onclick="return OpenAddForm()" class="btn btn-primary" style=" margin-top: 4%; margin-bottom:10px">Create</a>
<table id="FormTable" class="table table-bordered table-striped  js-basic-example dataTable">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Description</th>
            <th>Date</th>
            <th>Gender</th>
            <th>File</th>
           
            <th>Update</th>
            <th>Delete</th>


        </tr>



    </thead>
    <tbody>
    </tbody>

</table>

<script>
    $(function () {
        LoadDataGrid();
    })
    var OpenAddForm = function () {

        $.ajax({
            url: '/Fileextentions/Form',
            method: 'GET'
        }).done((data) => {
            $('#modal-trigger .title').text('Create');
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            toastr.error(response.responseText);
        })
    }
    var LoadDataGrid = function () {
        $.ajax({
            url: '/Fileextentions/LoadDataGrid',
            method: 'GET',
        }).done((data) => {
            var dtObj = {
                data: data,
                retrieve: true,
                ordering: true,
                responsive: true,
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search..."
                },
                dom: 'Bfrtip',
                columns: [
                    { 'data': 'id' },
                    { 'data': 'name' },
                    { 'data': 'description' },
                    { 'data': 'date' },
                    { 'data': 'gender.name' },
                  

                   
                    {
                        'data': 'filePath',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-primary" target="_balnk" href="' + Data + '">attach</a>';
                           

                            return rows;
                        }
                    },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-success" onclick="return Edit(' + Data + ')">Edit</a>';
                            return rows;
                        }
                    },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            rows += '<a class="btn btn-danger" onclick="return Delete(' + Data + ')">Delete</a>';
                            return rows;
                        }
                    }
                ]
            };

            $('#FormTable').dataTable().fnDestroy();
            $('#FormTable').dataTable(dtObj);
            $('#FormTable').css("width", "100%");
        });
    }
    var Delete = function (id) {
        $.ajax({
            url: '/Fileextentions/Delete',
            method: 'GET',
            data: {
                id: id
            }
        }).done((data) => {
            $('#modal-trigger .title').text("Delete");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            console.log(response.responseText);
        })
    }

    var Edit = function (Id) {

        $.ajax({
            url: '/Fileextentions/Form',
            method: 'GET',
            data: {
                Id: Id

            }
        }).done((data) => {
            $('#modal-trigger .title').text("Edit");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');

        }).fail(function (response) {
            toastr.error(response.responseText);
        })

    }
    
</script>