ProjectMohammadRepositry/Controllers/TransVisassController.cs
using Asp.Common.SessionConfig;
using Asp.DALL.Entites;
using Asp.DALL.Repositray;
using Asp.DALL.Viewmodel;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace ProjectMohammadRepositry.Controllers
{
    public class TransVisassController : BaseController
    {
        private readonly IRepositoryBase<TransVisa> _repo;
        private readonly IRepositoryBase<Gender> _listgender;
        private readonly IRepositoryBase<ListBooks> _listbooks;
        private readonly IRepositoryBase<Author> _listauthor;
        private IMapper _mapper;
        private IHostingEnvironment Environment;
        private ISessionConfigService _sessionConfigService;
        public TransVisassController(IRepositoryBase<TransVisa> repo,
                                     IRepositoryBase<Gender> listgender,
                                     IRepositoryBase<ListBooks> listbooks,
                                     IRepositoryBase<Author> listauthor,
                                     IMapper mapper,
                                     IHostingEnvironment _environment,
                                     ISessionConfigService SessionService
            ) : base(SessionService)
        {
            _repo = repo;
            _listgender = listgender;
            _listbooks = listbooks;
            _listauthor = listauthor;
            _mapper = mapper;
            Environment = _environment;
            _sessionConfigService = SessionService;

        }

        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> LoadDataGrid()
        {
            List<TransVisa> lists = await _repo.GetList(includes: new List<string> { "Gender", "ListBooks", "Author" });
            List<TransVisaVM> viewmodel = _mapper.Map<List<TransVisa>, List<TransVisaVM>>(lists);
            foreach (var item in viewmodel)
            {
                item.Filepath = "../Attachment/" + item.Id + "." + item.Extentions + "";

            }
            return Json(viewmodel);
        }
        public async Task<IActionResult> Form(int? id)
        {
            TransVisaVM vm = new TransVisaVM();
            ViewData["gender"] = await _listgender.GetList();
            ViewData["lists"] = await _listbooks.GetList();
            ViewData["Author"] = await _listauthor.GetList();
            if (id == 0 || id == null)
            {
                return PartialView(vm);

            }

            else
            {
                TransVisa entity = await _repo.GetOne(z => z.Id == id);
                vm = _mapper.Map<TransVisa, TransVisaVM>(entity);
                return PartialView(vm);
            }



        }
        [HttpPost]
        public async Task<IActionResult> Form(TransVisaVM insert)
        {
            TransVisa model;
            model = _mapper.Map<TransVisaVM, TransVisa>(insert);
            model.File = "../Attachment";
            var xx = Path.GetFileName(insert.Attach.FileName).Split(".");
            model.Extentions = Path.GetFileName(insert.Attach.FileName).Split(".")[xx.Count() - 1];
            bool done=false;

            if (insert.Id==0 || insert.Id==null)
            {
                done=await _repo.Add(model);

            }
            else
            {
                done=await _repo.Update(model);
            }
            if (insert.Attach != null)
            {
                string path = Path.Combine(this.Environment.WebRootPath, "Attachment");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }
                string name = model.Id.ToString() + "." + model.Extentions;
                using (FileStream stream = new FileStream(Path.Combine(path, name), FileMode.Create))
                {
                    insert.Attach.CopyTo(stream);
                }
            }
            return Json(new {done});

        }

        public async Task<IActionResult> Delete(int ? id)
        {
            return PartialView(await _repo.GetOne(z=>z.Id==id));

        }
        [HttpPost]
        public async Task<IActionResult> Delete(TransVisa del)
        {
            bool done = false;
            done = await _repo.Delete(del);
            return Json(new { done = done });

        }
    }
}

ProjectMohammadRepositry/Views/TransVisass/Delete.cshtml
@model Asp.DALL.Entites.TransVisa

<h1>Are you sure???????</h1>

<form asp-controller="TransVisass" asp-action="Delete" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">
    <input type="hidden" asp-for="Id" />

    <input type="submit" value="Delete" class="btn btn-danger" /> |
    <a asp-action="Index">Back to List</a>
</form>
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/TransVisass/Form.cshtml
@using Asp.DALL.Entites;
@model Asp.DALL.Viewmodel.TransVisaVM
@inject IHtmlLocalizer<MajalesResx> Localizer;
@{
    var listofgender = (List<Gender>)ViewData["gender"];
    var listofbooks = (List<ListBooks>)ViewData["lists"];
    var listofauthor = (List<Author>)ViewData["Author"];
}

<form asp-controller="TransVisass" asp-action="Form" data-ajax-method="post" data-ajax="true"
      data-ajax-failure="OnFailure"
      data-ajax-success="OnSuccess"
      data-ajax-begin="OnBegin"
      enctype="multipart/form-data">

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="File" />
    <input type="hidden" asp-for="Extentions" />
    <div class="row">
        <div class="col-lg-6">
            <label class="form-group">@Localizer["Name"]</label>
            <input class="form-control" type="text" asp-for="Name" />
        </div>
        <div class="col-lg-6">
            <label class="form-group">@Localizer["Description"]</label>
            <input class="form-control" type="text" asp-for="Description" />
        </div>
    </div>


    <br />
    <div class="row">
        <div class="col-lg-6">
            <label class="form-group">@Localizer["Age"]</label>
            <input class="form-control" type="number" asp-for="Age" />
        </div>
        <div class="col-lg-6">
            <label class="form-group">@Localizer["Title"]</label>
            <input class="form-control" type="text" asp-for="Title" />
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <label class="form-group">@Localizer["phone"]</label>
            <input class="form-control" type="number" asp-for="Phone" />
        </div>
        <div class="col-lg-6">
            <label class="form-group">@Localizer["email"]</label>
            <input class="form-control" type="email" asp-for="Email" />
        </div>
    </div>

    <br />
    <div class="row">
        <div class="col-lg-6">
            <label class="form-group">@Localizer["Date"]</label>
            <input class="form-control" type="date" asp-for="Date" />
        </div>
        <div class="col-lg-6">

            <label class="form-group">@Localizer["File"]</label>
            <input class="form-control" type="file" asp-for="Attach" />
        </div>
    </div>

    <br />

    <div class="row">
        <div class="col-lg-12">
            <label class="form-group">@Localizer["Author"]</label>
            <select class="form-control" asp-for="AuthorId">

                <option value="">Select Author</option>
                @foreach (var c in @listofauthor) // Print the list
                {
                    <option value="@c.Id">@c.Name</option>
                }


            </select>
        </div>
        <div class="col-lg-12">
            <label class="form-group">@Localizer["gender"]</label>
            <select class="form-control" asp-for="GenderId">

                <option value="">Select Author</option>
                @foreach (var c in @listofgender) // Print the list
                {
                    <option value="@c.Id">@c.Name</option>
                }


            </select>
        </div>
        <div class="col-lg-12">
            <label class="form-group">@Localizer["ListBooks"]</label>
            <select class="form-control" asp-for="Listid">

                <option value="">Select Author</option>
                @foreach (var c in @listofbooks) // Print the list
                {
                    <option value="@c.Id">@c.NameBooks</option>
                }


            </select>
        </div>
    </div>

    <br />
    <button class="btn btn-save"> save</button>
</form>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
<script>
    var OnFailure = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
    }
    var OnBegin = function () {
        $('form button').attr('disabled', true)
    }
    var OnSuccess = function (data) {
        $('form button').attr('disabled', false)
        console.log(data.message);
        LoadDataGrid();
        $('#modal-trigger .modal-body').html('');
        $('#modal-trigger').modal('hide');
    }
</script>

ProjectMohammadRepositry/Views/TransVisass/Index.cshtml
@inject IHtmlLocalizer<MajalesResx> Localizer;

<div class="row mb-4 justify-content-center">

    <div class="col-lg-10 animation">
        <div class="col">
            <a class="btn btn-ADD icon-move-right" href="javascript:void(0)" onclick="return OpenAddForm()"> <i class="bi bi-check2-all"></i>  @CommonLocalizer["Add"]</a>
        </div>
        <div class="card shadow ">
            <!-- Card Header - Dropdown -->
            <div class="card-header d-flex flex-row align-items-center">
                <div class="card-header-title">
                    <i class="bi bi-people icon-collapse   fa-2x"></i>
                    <label class="springy-text card-header-label">@Localizer["Transvisa"]</label>
                </div>

            </div>
            <!-- Card Body -->
            <div class="card-body">
                <div class="">
                    <table id="FormTable" class="table table-bordered table-striped  js-basic-example dataTable">
                        <thead>
                            <tr>
                                <th>@Localizer["Id"]</th>
                                <th>@Localizer["Name"]</th>
                                <th>@Localizer["Description"]</th>
                                <th>@Localizer["Title"]</th>
                                <th>@Localizer["Email"]</th>
                                <th>@Localizer["Age"]</th>
                                <th>@Localizer["Phone"]</th>
                                <th>@Localizer["Date"]</th>
                                <th>@Localizer["Author"]</th>
                                <th>@Localizer["gender"]</th>
                                <th>@Localizer["listbooks"]</th>
                                <th>@Localizer["File"]</th>
                                <th>@Localizer["Update"]</th>
                                <th>@Localizer["Delete"]</th>


                            </tr>



                        </thead>
                        <tbody>
                        </tbody>

                    </table>


                </div>
            </div>
        </div>
    </div>


</div>

<script>
    $(function () {
        LoadDataGrid();
    })
    var OpenAddForm = function () {

        $.ajax({
            url: '/TransVisass/Form',
            method: 'GET'
        }).done((data) => {
            $('#modal-trigger .title').text('Create');
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            toastr.error(response.responseText);
        })
    }
    var LoadDataGrid = function () {
        $.ajax({
            url: '/TransVisass/LoadDataGrid',
            method: 'GET',
        }).done((data) => {
            var dtObj = {
                data: data,
                retrieve: true,
                ordering: true,
                responsive: true,
                dom: 'Bfrtip',
                oLanguage: {
                    sSearch: '',
                    sSearchPlaceholder: "@CommonLocalizer["Search ..."]",
                },
                columns: [
                    { 'data': 'id' },
                    { 'data': 'name' },
                    { 'data': 'description' },
                    { 'data': 'title' },
                    { 'data': 'email' },
                    { 'data': 'age' },
                    { 'data': 'phone' },
                    { 'data': 'date' },
                    { 'data': 'author.name' },
                    { 'data': 'gender.name' },
                    { 'data': 'listid' },



                    {
                        'data': 'filepath',
                        'render': function (Data) {
                            var rows = '';
                            //rows += '<a class="btn btn-primary" target="_balnk" href="' + Data + '">attach</a>';
                            rows += '<a target="_blank" href="' + Data + '"> <i class="bi bi-eye icon-download"></i></a>';

                            return rows;
                        }
                    },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            //rows += '<a class="btn btn-success" onclick="return Edit(' + Data + ')">Edit</a>';
                            rows += '<a href="javascript:void(0)" onclick="return Edit(`' + Data + '`)"><i class="bi bi-pencil-square  icon-download"></i></a>';
                            return rows;
                        }
                    },
                    {
                        'data': 'id',
                        'render': function (Data) {
                            var rows = '';
                            //rows += '<a class="btn btn-danger" onclick="return Delete(' + Data + ')">Delete</a>';
                            rows += '<a href="javascript:void(0)" onclick="return Delete(`' + Data + '`)"><i class="bi bi-x-octagon  icon-delete"></i></a>';
                            return rows;
                        }
                    }
                ]
            };

            $('#FormTable').dataTable().fnDestroy();
            $('#FormTable').dataTable(dtObj);
            $('#FormTable').css("width", "100%");
        });
    }
    var Delete = function (id) {
        $.ajax({
            url: '/TransVisass/Delete',
            method: 'GET',
            data: {
                id: id
            }
        }).done((data) => {
            $('#modal-trigger .title').text("Delete");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');
        }).fail(function (response) {
            console.log(response.responseText);
        })
    }

    var Edit = function (Id) {

        $.ajax({
            url: '/TransVisass/Form',
            method: 'GET',
            data: {
                Id: Id

            }
        }).done((data) => {
            $('#modal-trigger .title').text("Edit");
            $('#modal-trigger .modal-body').html(data);
            $('#modal-trigger').modal('show');

        }).fail(function (response) {
            toastr.error(response.responseText);
        })

    }

</script>